apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-db-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: mysql-db
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pbapp-secrets
                key: db-password
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: pbapp-configmap
                key: dbuser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pbapp-secrets
                key: db-user-password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: pbapp-configmap
                key: dbname
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: storage-db

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql-db
  type: NodePort
