apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pbapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pbapp
    spec:
      containers:
      - name: pbapp
        image: docker.io/rfnovo/pbapp:v1
        ports:
        - name: http-port
          containerPort: 5000
        env:
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pbapp-secrets
                key: db-password
          - name: MYSQL_DB_USER
            valueFrom:
              configMapKeyRef:
                name: pbapp-configmap
                key: dbuser
          - name: MYSQL_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: pbapp-configmap
                key: dbname
          - name: MYSQL_DB_HOST
            value: mysql-db

---

apiVersion: v1
kind: Service
metadata:
  name: pbapp-web
spec:
  ports:
  - port: 80
    targetPort: http-port
    protocol: TCP
  selector:
    app: pbapp
  type: LoadBalancer
